[package]
name = "weaver-worldline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
weaver-core.workspace = true
simengine.workspace = true
glam.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true

[lints]
workspace = true
