[package]
name = "weaver-platform-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
weaver-core.workspace = true
weaver-app-core.workspace = true
weaver-render-wgpu.workspace = true
winit.workspace = true
wgpu.workspace = true
glam.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true

[dev-dependencies]
weaver-render.workspace = true

[lints]
workspace = true
