[package]
name = "space-lab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "space-lab"
path = "src/main.rs"

[dependencies]
weaver-app-core.workspace = true
weaver-render.workspace = true
weaver-render-wgpu.workspace = true
glam.workspace = true
chrono.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
weaver-platform-desktop.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
weaver-platform-web.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
