[package]
name = "space-lab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "space-lab"
path = "src/main.rs"

[dependencies]
weaver-app.workspace = true
weaver-core.workspace = true
weaver-render.workspace = true
weaver-render-wgpu.workspace = true
weaver-worldline.workspace = true
wgpu.workspace = true
glam.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true

[lints]
workspace = true
