[package]
name = "weaver-platform-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
weaver-app-core.workspace = true
weaver-render-wgpu.workspace = true
winit.workspace = true
wgpu.workspace = true
glam.workspace = true
pollster.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
weaver-render.workspace = true

[lints]
workspace = true
