[package]
name = "weaver-render-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
weaver-core.workspace = true
weaver-render.workspace = true
wgpu.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
glam.workspace = true
bytemuck.workspace = true
glyphon.workspace = true
image.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
pollster.workspace = true

[lints]
workspace = true
